version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    networks:
      - services-network
      - gateway-network
    volumes:
      - ./gateway:/gateway/
  user-service:
    build: ./user-service
    restart: always
    hostname: user-service
    env_file:
      - .env
    networks:
      - services-network
    volumes:
      - ./user-service:/user-service/
      - /user-service/node_modules
  auth-service:
    build: ./auth-service
    restart: always
    hostname: auth-service
    env_file:
      - .env
    networks:
      - services-network
      - gateway-network
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    volumes:
      - ./auth-service:/auth-service/
      - /auth-service/node_modules
  poll-service:
    build: ./poll-service
    restart: always
    hostname: poll-service
    env_file:
      - .env
    networks:
      - services-network
      - gateway-network
    ports:
      - ${POLL_SERVICE_PORT}:${POLL_SERVICE_PORT}
    volumes:
      - ./poll-service:/poll-service/
      - /poll-service/node_modules
  answer-service:
    build: ./answer-service
    restart: always
    hostname: answer-service
    env_file:
      - .env
    networks:
      - services-network
      - gateway-network
    ports:
      - ${ANSWER_SERVICE_PORT}:${ANSWER_SERVICE_PORT}
    volumes:
      - ./answer-service:/answer-service/
      - /answer-service/node_modules


  user-service-db:
    image: postgres
    hostname: ${POSTGRES_USER_SERVICE_DB_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_USER_SERVICE_DB}
      - POSTGRES_USER=${POSTGRES_USER_SERVICE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_USER_SERVICE_PASSWORD}
    ports:
      - 22222:${POSTGRES_USER_SERVICE_DB_PORT}
    networks:
      - services-network
      - gateway-network
  poll-service-db:
    image: postgres
    hostname: ${POSTGRES_POLL_SERVICE_DB_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_POLL_SERVICE_DB}
      - POSTGRES_USER=${POSTGRES_POLL_SERVICE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_POLL_SERVICE_PASSWORD}
    ports:
      - 22223:${POSTGRES_POLL_SERVICE_DB_PORT}
    networks:
      - services-network
      - gateway-network

  answer-service-db:
    image: postgres
    hostname: ${POSTGRES_ANSWER_SERVICE_DB_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_ANSWER_SERVICE_DB}
      - POSTGRES_USER=${POSTGRES_ANSWER_SERVICE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_ANSWER_SERVICE_PASSWORD}
    ports:
      - 22224:${POSTGRES_ANSWER_SERVICE_DB_PORT}
    networks:
      - services-network
      - gateway-network
networks:
  services-network:
    internal: true
  gateway-network:
    driver: bridge