version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    networks:
      - services-network-network
      - gateway-network
    volumes:
      - ./gateway:/src/
  user-service:
    build: ./user-service
    restart: always
    hostname: user-service
    env_file:
      - .env
    networks:
      - services-network-network
    volumes:
      - ./user-service:/src/
  auth-service:
    build: ./auth-service
    restart: always
    hostname: auth-service
    env_file:
      - .env
    networks:
      - services-network-network
    volumes:
      - ./auth-service:/src/
networks:
  services-network-network:
    internal: true
  gateway-network:
    driver: bridge