apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/jakubzygmunt/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/jakubzygmunt/kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/services-network: "true"
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        - name: REDIS_MASTER_PORT_NUMBER
          value: "6379"
        image: bitnami/redis:latest
        imagePullPolicy: ""
        name: redis
        resources:
          limits:
            cpu: 400m
            memory: "1073741824"
      hostname: redis
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
