export const POSTGRES_CONFIG = 'POSTGRES_CONFIG';
export const RABBITMQ_CONFIG = 'RABBITMQ_CONFIG';
export const POLL_SERVICE = 'POLL_SERVICE';
export const RESULT_SERVICE = 'RESULT_SERVICE';
export const ANSWER_UNIQUE_VIOLATION = '23505';
